name: Code Style Checks
on:
    push:
        paths:
            - "*"
    pull_request:
        branches:
            - main
            - dev
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                  npm install
                  npm run lint
